// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protofiles

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// UserDetailClient is the client API for UserDetail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserDetailClient interface {
	GetAllUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserDataResponse, error)
}

type userDetailClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDetailClient(cc grpc.ClientConnInterface) UserDetailClient {
	return &userDetailClient{cc}
}

func (c *userDetailClient) GetAllUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserDataResponse, error) {
	out := new(UserDataResponse)
	err := c.cc.Invoke(ctx, "/protofiles.UserDetail/GetAllUserData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDetailServer is the server API for UserDetail service.
// All implementations must embed UnimplementedUserDetailServer
// for forward compatibility
type UserDetailServer interface {
	GetAllUserData(context.Context, *UserDataRequest) (*UserDataResponse, error)
	mustEmbedUnimplementedUserDetailServer()
}

// UnimplementedUserDetailServer must be embedded to have forward compatible implementations.
type UnimplementedUserDetailServer struct {
}

func (UnimplementedUserDetailServer) GetAllUserData(context.Context, *UserDataRequest) (*UserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserData not implemented")
}
func (UnimplementedUserDetailServer) mustEmbedUnimplementedUserDetailServer() {}

// UnsafeUserDetailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDetailServer will
// result in compilation errors.
type UnsafeUserDetailServer interface {
	mustEmbedUnimplementedUserDetailServer()
}

func RegisterUserDetailServer(s *grpc.Server, srv UserDetailServer) {
	s.RegisterService(&_UserDetail_serviceDesc, srv)
}

func _UserDetail_GetAllUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailServer).GetAllUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.UserDetail/GetAllUserData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailServer).GetAllUserData(ctx, req.(*UserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDetail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.UserDetail",
	HandlerType: (*UserDetailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllUserData",
			Handler:    _UserDetail_GetAllUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_detail.proto",
}
